export interface GroupEmojiOption {
  value: string;
  label: string;
  shortcode: string;
  aliases: readonly string[];
}

export const GROUP_EMOJI_OPTIONS: readonly GroupEmojiOption[] = [
  { value: "📥", label: "Inbox", shortcode: "inbox_tray", aliases: ["inbox"] },
  {
    value: "🚧",
    label: "In progress",
    shortcode: "construction",
    aliases: ["wip", "working"],
  },
  {
    value: "🔥",
    label: "Urgent",
    shortcode: "fire",
    aliases: ["hot", "priority"],
  },
  {
    value: "🎯",
    label: "Goal",
    shortcode: "dart",
    aliases: ["target", "objective"],
  },
  {
    value: "💡",
    label: "Idea",
    shortcode: "bulb",
    aliases: ["lightbulb", "insight"],
  },
  {
    value: "✅",
    label: "Done",
    shortcode: "white_check_mark",
    aliases: ["complete", "completed", "check"],
  },
  {
    value: "🧭",
    label: "Planning",
    shortcode: "compass",
    aliases: ["plan", "direction"],
  },
  {
    value: "🛠️",
    label: "Tools",
    shortcode: "hammer_and_wrench",
    aliases: ["tooling", "maintenance"],
  },
  {
    value: "🔍",
    label: "Research",
    shortcode: "mag",
    aliases: ["search", "investigate"],
  },
  {
    value: "🧪",
    label: "Experiment",
    shortcode: "test_tube",
    aliases: ["test", "testing", "science"],
  },
  {
    value: "📌",
    label: "Pinned",
    shortcode: "pushpin",
    aliases: ["pin", "important"],
  },
  {
    value: "📝",
    label: "Notes",
    shortcode: "memo",
    aliases: ["write", "writing"],
  },
  {
    value: "📚",
    label: "Documentation",
    shortcode: "books",
    aliases: ["docs", "read"],
  },
  {
    value: "🗂️",
    label: "Organize",
    shortcode: "card_index_dividers",
    aliases: ["filing", "sort"],
  },
  {
    value: "💬",
    label: "Discussion",
    shortcode: "speech_balloon",
    aliases: ["chat", "conversation"],
  },
  {
    value: "👀",
    label: "Review",
    shortcode: "eyes",
    aliases: ["look", "inspect"],
  },
  {
    value: "🙋",
    label: "Needs input",
    shortcode: "raising_hand",
    aliases: ["question", "help", "blocked"],
  },
  {
    value: "🤝",
    label: "Collaboration",
    shortcode: "handshake",
    aliases: ["partner", "team"],
  },
  {
    value: "🚀",
    label: "Launch",
    shortcode: "rocket",
    aliases: ["ship", "deploy", "release"],
  },
  {
    value: "⚡",
    label: "Fast",
    shortcode: "zap",
    aliases: ["quick", "performance"],
  },
  {
    value: "🐛",
    label: "Bug",
    shortcode: "bug",
    aliases: ["fix", "issue", "defect"],
  },
  {
    value: "🎨",
    label: "Design",
    shortcode: "art",
    aliases: ["ui", "ux", "creative"],
  },
  {
    value: "📊",
    label: "Metrics",
    shortcode: "bar_chart",
    aliases: ["analytics", "data"],
  },
  {
    value: "🔒",
    label: "Security",
    shortcode: "lock",
    aliases: ["private", "secure"],
  },
  {
    value: "🌱",
    label: "Growth",
    shortcode: "seedling",
    aliases: ["new", "learning"],
  },
  {
    value: "🏁",
    label: "Finish",
    shortcode: "checkered_flag",
    aliases: ["flag", "milestone"],
  },
  {
    value: "😀",
    label: "Happy",
    shortcode: "grinning",
    aliases: ["smile", "glad"],
  },
  { value: "😂", label: "Joy", shortcode: "joy", aliases: ["laugh", "funny"] },
  {
    value: "🤔",
    label: "Thinking",
    shortcode: "thinking_face",
    aliases: ["consider", "hmm"],
  },
  {
    value: "🥳",
    label: "Celebrate",
    shortcode: "partying_face",
    aliases: ["party", "celebration"],
  },
  {
    value: "❤️",
    label: "Love",
    shortcode: "heart",
    aliases: ["favorite", "like"],
  },
  {
    value: "👍",
    label: "Approved",
    shortcode: "thumbsup",
    aliases: ["like", "yes", "+1"],
  },
  {
    value: "👎",
    label: "Rejected",
    shortcode: "thumbsdown",
    aliases: ["no", "-1"],
  },
  {
    value: "👏",
    label: "Applause",
    shortcode: "clap",
    aliases: ["congrats", "great"],
  },
  {
    value: "🙏",
    label: "Thanks",
    shortcode: "pray",
    aliases: ["please", "gratitude"],
  },
  {
    value: "🤖",
    label: "Automation",
    shortcode: "robot_face",
    aliases: ["robot", "bot", "ai"],
  },
  {
    value: "💻",
    label: "Development",
    shortcode: "computer",
    aliases: ["code", "coding", "laptop"],
  },
  {
    value: "⚙️",
    label: "Settings",
    shortcode: "gear",
    aliases: ["config", "configuration"],
  },
  {
    value: "🔧",
    label: "Fix",
    shortcode: "wrench",
    aliases: ["repair", "maintenance"],
  },
  {
    value: "🔨",
    label: "Build",
    shortcode: "hammer",
    aliases: ["construct", "compile"],
  },
  {
    value: "📦",
    label: "Package",
    shortcode: "package",
    aliases: ["bundle", "release"],
  },
  {
    value: "🧵",
    label: "Thread",
    shortcode: "thread",
    aliases: ["conversation", "session"],
  },
  {
    value: "🔗",
    label: "Link",
    shortcode: "link",
    aliases: ["url", "reference"],
  },
  {
    value: "📎",
    label: "Attachment",
    shortcode: "paperclip",
    aliases: ["file", "attach"],
  },
  {
    value: "📅",
    label: "Schedule",
    shortcode: "calendar",
    aliases: ["date", "event"],
  },
  {
    value: "⏰",
    label: "Deadline",
    shortcode: "alarm_clock",
    aliases: ["time", "due"],
  },
  {
    value: "⏳",
    label: "Waiting",
    shortcode: "hourglass_flowing_sand",
    aliases: ["pending", "later"],
  },
  {
    value: "⭐",
    label: "Star",
    shortcode: "star",
    aliases: ["favorite", "important"],
  },
  {
    value: "✨",
    label: "Polish",
    shortcode: "sparkles",
    aliases: ["magic", "improve"],
  },
  {
    value: "🎉",
    label: "Success",
    shortcode: "tada",
    aliases: ["party", "celebrate"],
  },
  {
    value: "🏆",
    label: "Winner",
    shortcode: "trophy",
    aliases: ["award", "achievement"],
  },
  {
    value: "💯",
    label: "Perfect",
    shortcode: "100",
    aliases: ["hundred", "score"],
  },
  {
    value: "❓",
    label: "Question",
    shortcode: "question",
    aliases: ["unknown", "help"],
  },
  {
    value: "❗",
    label: "Important",
    shortcode: "exclamation",
    aliases: ["attention", "priority"],
  },
  {
    value: "⚠️",
    label: "Warning",
    shortcode: "warning",
    aliases: ["caution", "risk"],
  },
  {
    value: "🚨",
    label: "Alert",
    shortcode: "rotating_light",
    aliases: ["incident", "emergency", "warning"],
  },
  {
    value: "🛡️",
    label: "Protection",
    shortcode: "shield",
    aliases: ["security", "defense"],
  },
  {
    value: "🔑",
    label: "Access",
    shortcode: "key",
    aliases: ["auth", "permission"],
  },
  {
    value: "📈",
    label: "Trending up",
    shortcode: "chart_with_upwards_trend",
    aliases: ["increase", "growth"],
  },
  {
    value: "📉",
    label: "Trending down",
    shortcode: "chart_with_downwards_trend",
    aliases: ["decrease", "decline"],
  },
  {
    value: "🧠",
    label: "Brainstorm",
    shortcode: "brain",
    aliases: ["think", "knowledge"],
  },
  {
    value: "☕",
    label: "Coffee",
    shortcode: "coffee",
    aliases: ["break", "cafe"],
  },
  {
    value: "🌐",
    label: "Web",
    shortcode: "globe_with_meridians",
    aliases: ["internet", "browser"],
  },
  {
    value: "🏠",
    label: "Home",
    shortcode: "house",
    aliases: ["homepage", "local"],
  },
  {
    value: "📁",
    label: "Folder",
    shortcode: "file_folder",
    aliases: ["directory", "files"],
  },
  {
    value: "🔄",
    label: "Refresh",
    shortcode: "arrows_counterclockwise",
    aliases: ["reload", "sync"],
  },
  {
    value: "🧹",
    label: "Cleanup",
    shortcode: "broom",
    aliases: ["clean", "chore"],
  },
  {
    value: "🧰",
    label: "Toolbox",
    shortcode: "toolbox",
    aliases: ["tools", "kit"],
  },
  {
    value: "🪄",
    label: "Magic",
    shortcode: "magic_wand",
    aliases: ["generate", "transform"],
  },
  { value: "😃", label: "Smiley", shortcode: "smiley", aliases: ["happy"] },
  { value: "😄", label: "Smile", shortcode: "smile", aliases: ["happy"] },
  {
    value: "😅",
    label: "Sweat smile",
    shortcode: "sweat_smile",
    aliases: ["relief", "nervous laugh"],
  },
  {
    value: "🤣",
    label: "Rolling on the floor laughing",
    shortcode: "rolling_on_the_floor_laughing",
    aliases: ["rofl", "lol"],
  },
  { value: "😉", label: "Wink", shortcode: "wink", aliases: ["joke"] },
  { value: "😊", label: "Blush", shortcode: "blush", aliases: ["pleased"] },
  {
    value: "😍",
    label: "Heart eyes",
    shortcode: "heart_eyes",
    aliases: ["love", "favorite"],
  },
  {
    value: "😎",
    label: "Sunglasses",
    shortcode: "sunglasses",
    aliases: ["cool"],
  },
  {
    value: "🙂",
    label: "Slight smile",
    shortcode: "slightly_smiling_face",
    aliases: ["okay", "friendly"],
  },
  {
    value: "🙃",
    label: "Upside down",
    shortcode: "upside_down_face",
    aliases: ["sarcasm", "silly"],
  },
  {
    value: "😐",
    label: "Neutral",
    shortcode: "neutral_face",
    aliases: ["meh"],
  },
  {
    value: "😑",
    label: "Expressionless",
    shortcode: "expressionless",
    aliases: ["blank"],
  },
  {
    value: "😒",
    label: "Unamused",
    shortcode: "unamused",
    aliases: ["annoyed"],
  },
  { value: "😓", label: "Sweat", shortcode: "sweat", aliases: ["stress"] },
  {
    value: "😔",
    label: "Pensive",
    shortcode: "pensive",
    aliases: ["sad", "thoughtful"],
  },
  {
    value: "😕",
    label: "Confused",
    shortcode: "confused",
    aliases: ["unsure"],
  },
  {
    value: "😱",
    label: "Scream",
    shortcode: "scream",
    aliases: ["shocked", "scared"],
  },
  { value: "😢", label: "Cry", shortcode: "cry", aliases: ["sad", "tear"] },
  { value: "😭", label: "Sob", shortcode: "sob", aliases: ["crying"] },
  { value: "😠", label: "Angry", shortcode: "angry", aliases: ["mad"] },
  { value: "😡", label: "Rage", shortcode: "rage", aliases: ["furious"] },
  {
    value: "🤯",
    label: "Mind blown",
    shortcode: "exploding_head",
    aliases: ["amazed", "wow"],
  },
  {
    value: "😴",
    label: "Sleeping",
    shortcode: "sleeping",
    aliases: ["tired", "snooze"],
  },
  {
    value: "🤓",
    label: "Nerd",
    shortcode: "nerd_face",
    aliases: ["geek", "smart"],
  },
  {
    value: "🧐",
    label: "Monocle",
    shortcode: "face_with_monocle",
    aliases: ["inspect", "curious"],
  },
  { value: "👋", label: "Wave", shortcode: "wave", aliases: ["hello", "bye"] },
  {
    value: "👌",
    label: "OK hand",
    shortcode: "ok_hand",
    aliases: ["okay", "approved"],
  },
  { value: "✌️", label: "Victory", shortcode: "v", aliases: ["peace"] },
  {
    value: "🤞",
    label: "Crossed fingers",
    shortcode: "crossed_fingers",
    aliases: ["hope", "luck"],
  },
  {
    value: "💪",
    label: "Muscle",
    shortcode: "muscle",
    aliases: ["strong", "effort"],
  },
  {
    value: "☝️",
    label: "Point up",
    shortcode: "point_up",
    aliases: ["above", "one"],
  },
  {
    value: "👉",
    label: "Point right",
    shortcode: "point_right",
    aliases: ["next"],
  },
  {
    value: "👇",
    label: "Point down",
    shortcode: "point_down",
    aliases: ["below"],
  },
  {
    value: "👈",
    label: "Point left",
    shortcode: "point_left",
    aliases: ["back"],
  },
  {
    value: "🙌",
    label: "Raised hands",
    shortcode: "raised_hands",
    aliases: ["celebrate", "hooray"],
  },
  {
    value: "👐",
    label: "Open hands",
    shortcode: "open_hands",
    aliases: ["welcome"],
  },
  {
    value: "🤷",
    label: "Shrug",
    shortcode: "person_shrugging",
    aliases: ["shrug", "unknown"],
  },
  { value: "✊", label: "Fist", shortcode: "fist", aliases: ["solidarity"] },
  {
    value: "✍️",
    label: "Writing hand",
    shortcode: "writing_hand",
    aliases: ["write", "draft"],
  },
  {
    value: "💅",
    label: "Nail care",
    shortcode: "nail_care",
    aliases: ["polish", "fancy"],
  },
  {
    value: "📋",
    label: "Clipboard",
    shortcode: "clipboard",
    aliases: ["tasks", "checklist"],
  },
  {
    value: "🔖",
    label: "Bookmark",
    shortcode: "bookmark",
    aliases: ["save", "marker"],
  },
  {
    value: "📄",
    label: "Page",
    shortcode: "page_facing_up",
    aliases: ["document", "file"],
  },
  {
    value: "📧",
    label: "Email",
    shortcode: "email",
    aliases: ["message", "mail"],
  },
  {
    value: "📨",
    label: "Incoming envelope",
    shortcode: "incoming_envelope",
    aliases: ["receive", "mail"],
  },
  {
    value: "📬",
    label: "Mailbox with mail",
    shortcode: "mailbox_with_mail",
    aliases: ["inbox", "message"],
  },
  {
    value: "🔔",
    label: "Bell",
    shortcode: "bell",
    aliases: ["notification", "alert"],
  },
  {
    value: "🔕",
    label: "Muted bell",
    shortcode: "no_bell",
    aliases: ["mute", "quiet"],
  },
  {
    value: "📣",
    label: "Megaphone",
    shortcode: "mega",
    aliases: ["announce", "broadcast"],
  },
  {
    value: "📢",
    label: "Loudspeaker",
    shortcode: "loudspeaker",
    aliases: ["announcement", "news"],
  },
  {
    value: "✏️",
    label: "Pencil",
    shortcode: "pencil2",
    aliases: ["edit", "write"],
  },
  {
    value: "📏",
    label: "Ruler",
    shortcode: "straight_ruler",
    aliases: ["measure", "size"],
  },
  {
    value: "📐",
    label: "Triangle ruler",
    shortcode: "triangular_ruler",
    aliases: ["measure", "design"],
  },
  { value: "✂️", label: "Scissors", shortcode: "scissors", aliases: ["cut"] },
  {
    value: "🗑️",
    label: "Wastebasket",
    shortcode: "wastebasket",
    aliases: ["trash", "delete"],
  },
  {
    value: "💾",
    label: "Floppy disk",
    shortcode: "floppy_disk",
    aliases: ["save", "storage"],
  },
  { value: "💿", label: "Disc", shortcode: "cd", aliases: ["disk", "media"] },
  {
    value: "📷",
    label: "Camera",
    shortcode: "camera",
    aliases: ["photo", "image"],
  },
  {
    value: "🎥",
    label: "Movie camera",
    shortcode: "movie_camera",
    aliases: ["video", "film"],
  },
  {
    value: "🎤",
    label: "Microphone",
    shortcode: "microphone",
    aliases: ["audio", "speak"],
  },
  {
    value: "🎧",
    label: "Headphones",
    shortcode: "headphones",
    aliases: ["audio", "listen"],
  },
  {
    value: "📞",
    label: "Telephone",
    shortcode: "telephone_receiver",
    aliases: ["call", "phone"],
  },
  {
    value: "🔌",
    label: "Plug",
    shortcode: "electric_plug",
    aliases: ["power", "integration"],
  },
  {
    value: "🔋",
    label: "Battery",
    shortcode: "battery",
    aliases: ["power", "energy"],
  },
  {
    value: "🧲",
    label: "Magnet",
    shortcode: "magnet",
    aliases: ["attract"],
  },
  {
    value: "📡",
    label: "Satellite antenna",
    shortcode: "satellite_antenna",
    aliases: ["signal", "network"],
  },
  {
    value: "🔬",
    label: "Microscope",
    shortcode: "microscope",
    aliases: ["research", "inspect"],
  },
  {
    value: "🔭",
    label: "Telescope",
    shortcode: "telescope",
    aliases: ["observe", "vision"],
  },
  {
    value: "⚗️",
    label: "Alembic",
    shortcode: "alembic",
    aliases: ["science", "experiment"],
  },
  { value: "🧬", label: "DNA", shortcode: "dna", aliases: ["biology", "gene"] },
  {
    value: "✔️",
    label: "Check mark",
    shortcode: "heavy_check_mark",
    aliases: ["yes", "verified"],
  },
  {
    value: "❌",
    label: "Cross mark",
    shortcode: "x",
    aliases: ["no", "failed"],
  },
  {
    value: "⛔",
    label: "No entry",
    shortcode: "no_entry",
    aliases: ["stop", "blocked"],
  },
  {
    value: "🚫",
    label: "Prohibited",
    shortcode: "no_entry_sign",
    aliases: ["forbidden", "disabled"],
  },
  {
    value: "‼️",
    label: "Double exclamation",
    shortcode: "bangbang",
    aliases: ["important", "urgent"],
  },
  {
    value: "⁉️",
    label: "Interrobang",
    shortcode: "interrobang",
    aliases: ["question", "surprise"],
  },
  {
    value: "ℹ️",
    label: "Information",
    shortcode: "information_source",
    aliases: ["info", "details"],
  },
  { value: "🆕", label: "New", shortcode: "new", aliases: ["fresh", "recent"] },
  { value: "🔜", label: "Soon", shortcode: "soon", aliases: ["upcoming"] },
  { value: "⬆️", label: "Up arrow", shortcode: "arrow_up", aliases: ["up"] },
  {
    value: "⬇️",
    label: "Down arrow",
    shortcode: "arrow_down",
    aliases: ["down"],
  },
  {
    value: "⬅️",
    label: "Left arrow",
    shortcode: "arrow_left",
    aliases: ["left"],
  },
  {
    value: "➡️",
    label: "Right arrow",
    shortcode: "arrow_right",
    aliases: ["right"],
  },
  {
    value: "🔁",
    label: "Repeat",
    shortcode: "repeat",
    aliases: ["loop", "again"],
  },
  {
    value: "🔀",
    label: "Shuffle",
    shortcode: "twisted_rightwards_arrows",
    aliases: ["random", "reorder"],
  },
  {
    value: "♾️",
    label: "Infinity",
    shortcode: "infinity",
    aliases: ["forever"],
  },
  {
    value: "🔴",
    label: "Red circle",
    shortcode: "red_circle",
    aliases: ["red"],
  },
  {
    value: "🟠",
    label: "Orange circle",
    shortcode: "orange_circle",
    aliases: ["orange"],
  },
  {
    value: "🟡",
    label: "Yellow circle",
    shortcode: "yellow_circle",
    aliases: ["yellow"],
  },
  {
    value: "🟢",
    label: "Green circle",
    shortcode: "green_circle",
    aliases: ["green"],
  },
  {
    value: "🔵",
    label: "Blue circle",
    shortcode: "large_blue_circle",
    aliases: ["blue"],
  },
  {
    value: "🟣",
    label: "Purple circle",
    shortcode: "purple_circle",
    aliases: ["purple"],
  },
  { value: "☀️", label: "Sun", shortcode: "sunny", aliases: ["sun", "bright"] },
  { value: "☁️", label: "Cloud", shortcode: "cloud", aliases: ["cloudy"] },
  {
    value: "🌧️",
    label: "Rain cloud",
    shortcode: "rain_cloud",
    aliases: ["rain", "weather"],
  },
  {
    value: "❄️",
    label: "Snowflake",
    shortcode: "snowflake",
    aliases: ["snow", "cold"],
  },
  {
    value: "🌊",
    label: "Ocean",
    shortcode: "ocean",
    aliases: ["wave", "water"],
  },
  { value: "⛰️", label: "Mountain", shortcode: "mountain", aliases: ["peak"] },
  {
    value: "🌲",
    label: "Evergreen tree",
    shortcode: "evergreen_tree",
    aliases: ["forest", "pine"],
  },
  {
    value: "🌳",
    label: "Deciduous tree",
    shortcode: "deciduous_tree",
    aliases: ["tree", "nature"],
  },
  { value: "🌵", label: "Cactus", shortcode: "cactus", aliases: ["desert"] },
  { value: "🌿", label: "Herb", shortcode: "herb", aliases: ["leaf", "plant"] },
  {
    value: "🍀",
    label: "Four leaf clover",
    shortcode: "four_leaf_clover",
    aliases: ["luck", "lucky"],
  },
  {
    value: "🌎",
    label: "Earth",
    shortcode: "earth_americas",
    aliases: ["world", "global"],
  },
  {
    value: "🌙",
    label: "Crescent moon",
    shortcode: "crescent_moon",
    aliases: ["night", "moon"],
  },
  { value: "🌈", label: "Rainbow", shortcode: "rainbow", aliases: ["color"] },
  {
    value: "✈️",
    label: "Airplane",
    shortcode: "airplane",
    aliases: ["flight", "travel"],
  },
  { value: "🚗", label: "Car", shortcode: "car", aliases: ["drive", "road"] },
  {
    value: "🚆",
    label: "Train",
    shortcode: "train2",
    aliases: ["rail", "travel"],
  },
  { value: "🚢", label: "Ship", shortcode: "ship", aliases: ["boat", "sail"] },
  {
    value: "⚓",
    label: "Anchor",
    shortcode: "anchor",
    aliases: ["stable", "ship"],
  },
  {
    value: "🗺️",
    label: "World map",
    shortcode: "world_map",
    aliases: ["map", "travel"],
  },
  { value: "🐶", label: "Dog", shortcode: "dog", aliases: ["puppy", "pet"] },
  { value: "🐱", label: "Cat", shortcode: "cat", aliases: ["kitten", "pet"] },
  { value: "🦊", label: "Fox", shortcode: "fox_face", aliases: ["animal"] },
  { value: "🐻", label: "Bear", shortcode: "bear", aliases: ["animal"] },
  { value: "🐼", label: "Panda", shortcode: "panda_face", aliases: ["animal"] },
  { value: "🐨", label: "Koala", shortcode: "koala", aliases: ["animal"] },
  { value: "🦉", label: "Owl", shortcode: "owl", aliases: ["bird", "wise"] },
  {
    value: "🦋",
    label: "Butterfly",
    shortcode: "butterfly",
    aliases: ["change", "insect"],
  },
  {
    value: "🐝",
    label: "Bee",
    shortcode: "bee",
    aliases: ["honeybee", "insect"],
  },
  {
    value: "🐳",
    label: "Whale",
    shortcode: "whale",
    aliases: ["ocean", "animal"],
  },
  {
    value: "🐙",
    label: "Octopus",
    shortcode: "octopus",
    aliases: ["ocean", "animal"],
  },
  {
    value: "🦄",
    label: "Unicorn",
    shortcode: "unicorn_face",
    aliases: ["magic", "rare"],
  },
  {
    value: "🐢",
    label: "Turtle",
    shortcode: "turtle",
    aliases: ["slow", "animal"],
  },
  {
    value: "🐧",
    label: "Penguin",
    shortcode: "penguin",
    aliases: ["bird", "cold"],
  },
  { value: "🍕", label: "Pizza", shortcode: "pizza", aliases: ["food"] },
  {
    value: "🍔",
    label: "Hamburger",
    shortcode: "hamburger",
    aliases: ["burger", "food"],
  },
  {
    value: "🍎",
    label: "Apple",
    shortcode: "apple",
    aliases: ["fruit", "food"],
  },
  { value: "🥑", label: "Avocado", shortcode: "avocado", aliases: ["food"] },
  {
    value: "🎂",
    label: "Birthday cake",
    shortcode: "birthday",
    aliases: ["cake", "celebrate"],
  },
  {
    value: "🍪",
    label: "Cookie",
    shortcode: "cookie",
    aliases: ["snack", "food"],
  },
  {
    value: "🍿",
    label: "Popcorn",
    shortcode: "popcorn",
    aliases: ["movie", "snack"],
  },
  {
    value: "⚽",
    label: "Soccer",
    shortcode: "soccer",
    aliases: ["football", "sport"],
  },
  {
    value: "🏀",
    label: "Basketball",
    shortcode: "basketball",
    aliases: ["sport"],
  },
  {
    value: "🎮",
    label: "Video game",
    shortcode: "video_game",
    aliases: ["gaming", "play"],
  },
  {
    value: "🎲",
    label: "Game die",
    shortcode: "game_die",
    aliases: ["dice", "random"],
  },
  {
    value: "🎵",
    label: "Music",
    shortcode: "musical_note",
    aliases: ["song", "audio"],
  },
  {
    value: "🎁",
    label: "Gift",
    shortcode: "gift",
    aliases: ["present", "surprise"],
  },
  {
    value: "🧩",
    label: "Puzzle",
    shortcode: "jigsaw",
    aliases: ["piece", "solve"],
  },
];

function normalizeSearchText(value: string): string {
  return value
    .trim()
    .toLocaleLowerCase()
    .replace(/^:+|:+$/gu, "")
    .replace(/[_-]+/gu, " ")
    .replace(/\s+/gu, " ");
}

function matchScore(option: GroupEmojiOption, query: string): number | null {
  if (option.value === query) return 0;
  const terms = [option.label, option.shortcode, ...option.aliases].map(
    normalizeSearchText,
  );
  if (terms.some((term) => term === query)) return 1;
  if (terms.some((term) => term.startsWith(query))) return 2;
  if (terms.some((term) => term.includes(query))) return 3;
  return null;
}

export function searchGroupEmojis(
  rawQuery: string,
): readonly GroupEmojiOption[] {
  const query = normalizeSearchText(rawQuery);
  if (!query) return GROUP_EMOJI_OPTIONS;

  return GROUP_EMOJI_OPTIONS.map((option, index) => ({
    index,
    option,
    score: matchScore(option, query),
  }))
    .filter(
      (
        result,
      ): result is { index: number; option: GroupEmojiOption; score: number } =>
        result.score !== null,
    )
    .sort((left, right) => left.score - right.score || left.index - right.index)
    .map(({ option }) => option);
}
